services:
  mongo:
    image: mongo:7
    container_name: mini-jira-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mini-jira
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
